apiVersion: v1
kind: Service
metadata:
  name: demo-metrics
  namespace: apps
  labels:
    app: demo-metrics
spec:
  selector:
    app: demo-metrics
  ports:
    - name: http
      port: 8080
      targetPort: http
