grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 30000
  defaultDashboardsEnabled: true

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30090

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true

alertmanager:
  enabled: false
